-- script.sql

-- Tạo bảng TRINHDO
CREATE TABLE TRINHDO (
    MATD INTEGER PRIMARY KEY,
    TENTD VARCHAR(50) NOT NULL
);

-- Tạo bảng CAPBAC
CREATE TABLE CAPBAC (
    MABAC VARCHAR(10) PRIMARY KEY,
    TENBAC VARCHAR(50) NOT NULL
);

-- Tạo bảng NGACH
CREATE TABLE NGACH (
    MANGACH VARCHAR(10) PRIMARY KEY,
    TENNGACH VARCHAR(50) NOT NULL
);

-- Tạo bảng HESOLUONG
CREATE TABLE HESOLUONG (
    MABAC VARCHAR(10) REFERENCES CAPBAC(MABAC),
    MANGACH VARCHAR(10) REFERENCES NGACH(MANGACH),
    HESO FLOAT NOT NULL
);

-- Tạo bảng GIANGVIEN
CREATE TABLE GIANGVIEN (
    MAGIANGVIEN VARCHAR(8) PRIMARY KEY,
    MATD INTEGER REFERENCES TRINHDO(MATD),
    MANGACH VARCHAR(10) REFERENCES NGACH(MANGACH),
    HOTEN VARCHAR(50) NOT NULL,
    NGAYSINH VARCHAR(10) NOT NULL,
    GIOITINH BOOLEAN NOT NULL,
    SODIENTHOAI VARCHAR(10),
    DIACHI VARCHAR(100),
    MABAC VARCHAR(10) REFERENCES CAPBAC(MABAC),
    NGAYVAOLAM VARCHAR(10),
    CHUCVU VARCHAR(50),
    SOTIETDAY INTEGER
);

-- Tạo bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    giang_vien VARCHAR(8) REFERENCES GIANGVIEN(MAGIANGVIEN),
    MATKHAU VARCHAR(50) NOT NULL,
    PRIMARY KEY (giang_vien)
);
