from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('hieutruong/', views.login_hieutruong, name='login_hieutruong'),
    path('giangvien/', views.login_giangvien, name='login_giangvien'),
    path('ketoan/', views.login_ketoan, name='login_ketoan'),
    path('emp_home/', views.emp_home, name='emp_home'),
    path('profile/', views.profile, name='profile'),
    path('search/', views.search, name='search'),
    path('update_salary1/', views.update_salary1, name='update_salary1'),
    path('view/<int:magiangvien>/', views.view, name='view'),
    path('salary_slip/<int:magiangvien>/',
         views.salary_slip, name='salary_slip'),
    path('hieutruong_home/', views.hieutruong_home, name='hieutruong_home'),
    path('hieutruong_profile/', views.hieutruong_profile,
         name='hieutruong_profile'),
    path('hieutruong_search/', views.hieutruong_search, name='hieutruong_search'),
    path('hieutruong_view/<int:magiangvien>/',
         views.hieutruong_view, name='hieutruong_view'),
    path('hieutruong_salary_slip/<str:magiangvien>/',
         views.hieutruong_salary_slip, name='hieutruong_salary_slip'),
     path('hieutruong_update/<str:magiangvien>/',
          views.hieutruong_update, name='hieutruong_update'),
    path('giangvien_home/', views.giangvien_home, name='giangvien_home'),
    path('giangvien_profile/', views.giangvien_profile,
         name='giangvien_profile'),
    path('logout_giangvien/', views.logout_giangvien, name='logout_giangvien'),
    path('logout_ketoan/', views.logout_ketoan, name='logout_ketoan'),
    path('logout_hieutruong/', views.logout_hieutruong, name='logout_hieutruong'),
    path('giangvien_search/', views.giangvien_search, name='giangvien_search'),
    path('giangvien_view/<int:magiangvien>/',
         views.giangvien_view, name='giangvien_view'),
]
